---
rancher_server: "{{ hostvars['rancher']['ansible_ssh_host'] }}"
rancher_name: wurstbehavior
rancher_port: 8080

# MySQL variables
mysql_root_password: "{{ lookup('password', mysql_passwd_tmpfile + ' length=20 chars=ascii_letters,digits') }}"
mysql_passwd_tmpfile: /tmp/mysqlpasswd.file
mysql_host: "{{ hostvars.node2.mysql_sec_ip.stdout }}"
mysql_port: 3306
mysql_version: 5.5

# Wordpress variables
wordpress_version: latest
