---
- name: Installing and configuring Docker
  hosts: all
  become: yes
  roles:
    - { role: application/docker, tags: ["docker"] }

- name: Deploy MySQL 
  hosts: "database"
  become: yes
  roles:
      - { role: application/mysql_docker, tags: ["mysql_docker"] }

- name: Deploy Wordpress
  hosts: "application"
  become: yes
  roles:
    - { role: application/wordpress_docker, tags: ["wordpress_docker"] }
