# MySQL 
mysql_root_password: "{{ lookup('password', mysql_passwd_tmpfile + ' length=20 chars=ascii_letters,digits') }}"
mysql_passwd_tmpfile: /tmp/mysqlpasswd.file
#mysql_host: "{{ hostvars.node2.mysql_sec_ip.stdout }}"
mysql_host_nat: 10.12.0.117
mysql_port: 8000

# Wordpress 
wordpress_host_vbox: 192.168.0.248 
wordpress_version: latest
wordpress_port: 80
wordpress_db_user: wp-remote-user
wordpress_db_password: 12345
wordpress_db_name: wp
